[project]
name = "XMLPy"
version = "0.0.1"
description = "Adds html and basic html templating to python."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]