# Source: .\main.xmlpy, generated by xmlpy at 17/07/2022 09:09:27
class Element:
  def __init__(self, name, attributes, children):
    self.name = name
    self.attributes = attributes
    self.children = children

  def __repr__(self):
    return '<Element %s, %s, %s>' % (self.name, self.attributes, self.children)

def createEl(name, attributes, children):
  return Element(name, attributes, children)

h1cont = "world!"

element = (
  createEl('div', {'attribute': 'value', 'style': {
      "color": "red",
      "background": "green"
    }}, [createEl('h1', {}, [f"Hello {h1cont.upper()}"]), createEl('h2', {}, [f"Child 2"]), createEl('div', {}, [createEl('span', {}, [f"Some text"])])])
)

if element.attributes["style"]["color"] == "red":
  print("color is red")

print(element)