# Source: tests/test.xmlpy, generated by xmlpy at 30/11/2022 20:49:56
class XMLPyElement:
  def __init__(self, name, attributes, children):
    self.name = name
    self.attributes = attributes
    self.children = children

  def __repr__(self):
    return '<Element %s, %s, %s>' % (self.name, self.attributes, self.children)

h1cont = "world!"

print(5 < 10)

"""
<h1>Hello, World!</h1>
"""

class CostumEl: pass

element = (
  XMLPyElement('div', {'attribute': 'value', 'style': {
      "color": "red",
      "background": "green"
    }, 'other': "something"}, [XMLPyElement(CostumEl, {'something': "yes"}, []), XMLPyElement('h1', {}, ["Hello "+h1cont.upper()+""]), XMLPyElement('h2', {}, ["Child 2"]), XMLPyElement('div', {}, [XMLPyElement('span', {}, ["Some text"])])])
)

if element.attributes["style"]["color"] == "red":
  print("color is red")

print(element)