# Source: test.xmlpy, generated by xmlpy at 17/06/2023 16:12:07
class PyElement:
  def __init__(self, name, attributes, children):
    self.name = name
    self.attributes = attributes
    self.children = children

  def __repr__(self):
    return '<Element %s, %s, %s>' % (self.name, self.attributes, self.children)

h1cont = "world!"

print(5 < 10)

"""
<h1>Hello, World!</h1>
"""

class CostumEl: pass

element = (
  PyElement('div', {'attribute': 'value', 'style': {
      "color": "red",
      "background": "green"
    }, 'other': "something"}, [PyElement(CostumEl, {'something': "yes"}, []), PyElement('h1', {}, ["Hello ",h1cont.upper(),""]), PyElement('h2', {}, ["Child 2"]), PyElement('div', {}, [PyElement('span', {}, ["Some text"])])])
)

if element.attributes["style"]["color"] == "red":
  print("color is red")

print(element)