# Source: .\tests\test.xmlpy, generated by xmlpy at 17/07/2022 09:35:25
class XMLPyElement:
  def __init__(self, name, attributes, children):
    self.name = name
    self.attributes = attributes
    self.children = children

  def __repr__(self):
    return '<Element %s, %s, %s>' % (self.name, self.attributes, self.children)

h1cont = "world!"

element = (
  XMLPyElement('div', {'attribute': 'value', 'style': {
      "color": "red",
      "background": "green"
    }}, [XMLPyElement('h1', {}, [f"Hello {h1cont.upper()}"]), XMLPyElement('h2', {}, [f"Child 2"]), XMLPyElement('div', {}, [XMLPyElement('span', {}, [f"Some text"])])])
)

if element.attributes["style"]["color"] == "red":
  print("color is red")

print(element)